# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger-test:
    # The type of runner that the job will run on
    runs-on: [ "self-hosted" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout test
        uses: actions/checkout@v2
        
      - name: test echo
        run: echo "Test From repo"

      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: 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
          repository: poohSky/dispatch_To
          event-type: trigger-workflow
          client-payload: '{"github": ${{ toJson(github) }}}'
          
   #     uses: actions/github-script@v6
   #     with:
   #      github-token: ${{ secrets.G_ACCESS_TOKEN }}
   #      script: |
   #        await github.rest.actions.createWorkflowDispatch({
   #         owner: 'poohSky',
   #         repo: 'dispatch_To',
   #         workflow_id: 'buildTest.yml',
   #         ref: 'main'
   #        })
