# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ "self-hosted" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: test checkout
        uses: actions/checkout@v3

      - name: test echo
        run: echo "Test From repo"

      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: "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"
          repository: poohSky/dispatch_To
          event-type: trigger-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          
          
      # uses: actions/github-script@v6
      # with:
      #  github-token: "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"
      #  script: |
      #    await github.rest.actions.createWorkflowDispatch({
      #     owner: 'poohSky',
      #     repo: 'dispatch_To',
      #     workflow_id: 'buildTest.yml',
      #     ref: 'main'
      #    })
